apiDir: "../headless-vitamins-api/src/main/java"
apiPackagePath: "com.denbinger.headless.vitamins"
application:
    baseURI: "/headless-vitamins"
    className: "HeadlessVitaminsApplication"
    name: "HeadlessVitamins"
author: "jinos"
clientDir: "../headless-vitamins-client/src/main/java"
testDir: "../headless-vitamins-test/src/testIntegration/java"